export const baseComponents = [
  ['Accordion', 'accordion.tsx'],
  ['Alert', 'alert.tsx'],
  ['Alert Dialog', 'alert-dialog.tsx'],
  ['Aspect Ratio', 'aspect-ratio.tsx'],
  ['Avatar', 'avatar.tsx'],
  ['Badge', 'badge.tsx'],
  ['Breadcrumb', 'breadcrumb.tsx'],
  ['Button', 'button.tsx'],
  ['Button Group', 'button-group.tsx'],
  ['Calendar', 'calendar.tsx'],
  ['Card', 'card.tsx'],
  ['Carousel', 'carousel.tsx'],
  ['Chart', 'chart.tsx'],
  ['Checkbox', 'checkbox.tsx'],
  ['Collapsible', 'collapsible.tsx'],
  ['Command', 'command.tsx'],
  ['Context Menu', 'context-menu.tsx'],
  ['Date Picker', 'date-picker.tsx'],
  ['Dialog', 'dialog.tsx'],
  ['Drawer', 'drawer.tsx'],
  ['Dropdown Menu', 'dropdown-menu.tsx'],
  ['Empty', 'empty.tsx'],
  ['Field', 'field.tsx'],
  ['Form', 'form.tsx'],
  ['Hover Card', 'hover-card.tsx'],
  ['Input', 'input.tsx'],
  ['Input Group', 'input-group.tsx'],
  ['Input OTP', 'input-otp.tsx'],
  ['Item', 'item.tsx'],
  ['Kbd', 'kbd.tsx'],
  ['Label', 'label.tsx'],
  ['Menubar', 'menubar.tsx'],
  ['Navigation Menu', 'navigation-menu.tsx'],
  ['Pagination', 'pagination.tsx'],
  ['Popover', 'popover.tsx'],
  ['Progress', 'progress.tsx'],
  ['Radio Group', 'radio-group.tsx'],
  ['Resizable', 'resizable.tsx'],
  ['Scroll Area', 'scroll-area.tsx'],
  ['Select', 'select.tsx'],
  ['Separator', 'separator.tsx'],
  ['Sheet', 'sheet.tsx'],
  ['Sidebar', 'sidebar.tsx'],
  ['Skeleton', 'skeleton.tsx'],
  ['Slider', 'slider.tsx'],
  ['Sonner', 'sonner.tsx'],
  ['Spinner', 'spinner.tsx'],
  ['Switch', 'switch.tsx'],
  ['Table', 'table.tsx'],
  ['Tabs', 'tabs.tsx'],
  ['Textarea', 'textarea.tsx'],
  ['Toggle', 'toggle.tsx'],
  ['Toggle Group', 'toggle-group.tsx'],
  ['Tooltip', 'tooltip.tsx'],
  ['Leaflet Map', 'leaflet-map.tsx'],
  ['Map', 'map.tsx'],
] as const

export type BaseComponentName = (typeof baseComponents)[number][0]

